<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logs.proto

namespace App\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>logs.LogRequest</code>
 */
class LogRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.logs.Log logEntry = 1;</code>
     */
    protected $logEntry = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Proto\Log $logEntry
     * }
     */
    public function __construct($data = NULL) {
        \App\Proto\GPBMetadata\Logs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.logs.Log logEntry = 1;</code>
     * @return \App\Proto\Log|null
     */
    public function getLogEntry()
    {
        return $this->logEntry;
    }

    public function hasLogEntry()
    {
        return isset($this->logEntry);
    }

    public function clearLogEntry()
    {
        unset($this->logEntry);
    }

    /**
     * Generated from protobuf field <code>.logs.Log logEntry = 1;</code>
     * @param \App\Proto\Log $var
     * @return $this
     */
    public function setLogEntry($var)
    {
        GPBUtil::checkMessage($var, \App\Proto\Log::class);
        $this->logEntry = $var;

        return $this;
    }

}

